server:
  port: 80
eureka:
  client:
    register-with-eureka: false #客户端不注册到eureka，只是进行服务的调用
    service-url:
      defaultZone: http://eureka-7001:7001/eureka,http://eureka-7002:7002/eureka,http://eureka-7003:7003/eureka
feign:
  compression:
    request:
      mime-types:       # 可以被压缩的类型
      - text/xml
      - application/xml
      - application/json
      min-request-size: 2048 # 超过2048的字节进行压缩