server:
  port: 8005
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml    # mybatis配置文件所在路径
  type-aliases-package: com.hjl.bean            # 定义所有操作类的别名所在包
  mapper-locations:                                     # 所有的mapper映射文件
  - classpath:mybatis/mapper/**/*.xml
spring:
  application:
    name: cloud-provider
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource    # 配置当前要使用的数据源的操作类型
    driver-class-name: org.gjt.mm.mysql.Driver      # 配置MySQL的驱动程序类
    url: jdbc:mysql://localhost:3306/cloud           # 数据库连接地址
    username: root                                  # 数据库用户名
    password: root                            # 数据库连接密码
    dbcp2:                                          # 进行数据库连接池的配置
      min-idle: 5                                   # 数据库连接池的最小维持连接数
      initial-size: 5                               # 初始化提供的连接数
      max-total: 5                                  # 最大的连接数
      max-wait-millis: 200                          # 等待连接获取的最大超时时间
security:
  basic:
    enabled: true # 启用SpringSecurity的安全配置项
  user:
    name: hello  # 认证用户名
    password: hello # 认证密码
    role:        # 授权角色
    - USER
  sessions: always
eureka:
  client: # 客户端进行Eureka注册的配置
    service-url:
      defaultZone: http://eureka-7001:7001/eureka, http://eureka-7002:7002/eureka, http://eureka-7003:7003/eureka
    instance:
        instance-id: dept-8001  # 在信息列表时显示主机名称
feign:
  hystrix:
    enabled: true