spring:
  application:
    name: microcloud-config-client  # 编写应用的名称
server:
  port: 8888
eureka:
  client:
    service-url:
      defaultZone: http://eureka-7001:7001/eureka, http://eureka-7002:7002/eureka, http://eureka-7003:7003/eureka