server:
  port: 9501

eureka:
  client: # 客户端进行Eureka注册的配置
    service-url:
      defaultZone: http://eureka-7001:7001/eureka,http://eureka-7002:7002/eureka,http://eureka-7003:7003/eureka
  instance:
    lease-renewal-interval-in-seconds: 2 # 设置心跳的时间间隔（默认是30秒）
    lease-expiration-duration-in-seconds: 5 # 如果现在超过了5秒的间隔（默认是90秒）
    instance-id: gateway-9501.com  # 在信息列表时显示主机名称
    prefer-ip-address: true     # 访问的路径变为IP地址

info:
  app.name: study-microcloud
  company.name: www.study.cn
  build.artifactId: $project.artifactId$
  build.version: $project.verson$

spring:
  application:
    name: microcloud-zuul-gateway
zuul:
  ignored-services:
    cloud-provider
  routes:
    cloud-provider: /company-proxy/**
#zuul:
#   ignored-services:
#    "*"
#  routes:
#   mycompany.path: /company-proxy/**
#   mycompany.serviceId: cloud-provider
#zuul:
#   ignored-services:
#    "*"
#   routes:
#    company.path: /company-proxy/**
#    company.url: http://http://dept-8001:8001/